# Generated by Django 4.0.1 on 2022-02-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_alter_autor_options_alter_autor_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('fecha_impresion', models.DateField(max_length=255, verbose_name='Título')),
                ('editorial', models.CharField(max_length=255)),
                ('coleccion', models.CharField(max_length=255)),
                ('edicion', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('lugar_impresion', models.CharField(max_length=255)),
                ('notas', models.TextField()),
                ('autor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libro.autor')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
    ]
