# Generated by Django 4.0.1 on 2022-02-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='archivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=255)),
                ('subserie', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('numero_hojas', models.IntegerField()),
                ('lugar_expedicion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_impresion',
            field=models.DateField(),
        ),
    ]
